// Main-authored M6/M7 regression; not a new independent role report.
import { chromium } from '../frontend/node_modules/playwright/index.mjs';
import playwrightTest from '../frontend/node_modules/@playwright/test/index.js';
const { expect } = playwrightTest;
import fs from 'node:fs/promises';
import crypto from 'node:crypto';
const [url,,out]=process.argv.slice(2);
await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:process.env.KOSMOS_BROWSER_CHANNEL||'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1366,height:900},acceptDownloads:true});
const page=await context.newPage();
const proof={author:'Main; direct execution authorized by user',browser:browser.version(),checks:[],errors:[],console:[],external:[],environmentInjection:[],downloads:[],screens:[]};
let phase='startup';
page.on('pageerror',e=>proof.errors.push(e.message));
page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')proof.console.push({type:m.type(),text:m.text(),phase,expected:['invalid JSON preserves settings and hides results','controlled server error and retry'].includes(phase)});});
page.on('request',r=>{if(!r.url().startsWith(url)&&!r.url().startsWith('blob:')){const target=new URL(r.url());if(target.hostname==='gc.kis.v2.scr.kaspersky-labs.com'&&target.pathname.endsWith('/main.js'))proof.environmentInjection.push(r.url());else proof.external.push(r.url());}});
const check=async(name,fn)=>{phase=name;await fn();proof.checks.push(name);phase='between checks';};
const cost=()=>page.getByTestId('metric-c0_mrub').locator('strong');
const waitCost=async(text='1 150,8')=>expect(cost()).toHaveText(text,{timeout:30000});
const load=()=>page.getByRole('button',{name:'Загрузить сохранённый состав в конструктор',exact:true});
const screenshot=async(name,locator=page)=>{await locator.screenshot({path:out+'/'+name+'.png'});proof.screens.push(name+'.png');};
const setRows=async(rows)=>{await page.getByRole('button',{name:'Сбросить всё',exact:true}).click();for(let i=0;i<rows.length;i++){await page.getByLabel('Лот '+(i+1),{exact:true}).selectOption(rows[i][0]);await page.getByLabel('Режим '+(i+1),{exact:true}).selectOption(rows[i][1]);}};
try {
 await page.route('**/api/case',async route=>{await new Promise(r=>setTimeout(r,300));await route.continue();});
 await page.goto(url);
 await check('loading state',()=>expect(page.getByRole('heading',{name:'Загрузка кейса'})).toBeVisible());
 await load().waitFor({timeout:90000});
 await check('six navigation sections',async()=>{for(const name of ['Обзор','Конструктор','Сравнение','Стресс-сценарий','Показатели команды','Реализация и материалы'])await expect(page.getByRole('navigation').getByRole('link',{name,exact:true})).toBeVisible();});
 await check('empty and incomplete states',async()=>{await expect(page.locator('#comparison .empty')).toBeVisible();await expect(page.locator('#stress')).toContainText('Сначала выберите четыре лота');});
 await screenshot('overview-laptop');
 await load().click();await waitCost();
 await check('saved portfolio metrics',async()=>{for(const [key,value] of [['opex_mrub_per_year','311'],['cash_mrub_per_year','410,5'],['vpub_mrub_per_year','1 239'],['kcash','1,319936']])await expect(page.getByTestId('metric-'+key).locator('strong')).toHaveText(value);});
 await check('BASE and STRESS cap only',async()=>{await expect(page.getByTestId('stress-summary-BASE')).toContainText('+149,2');await expect(page.getByTestId('stress-summary-STRESS')).toContainText('+29,2');await page.getByRole('button',{name:'Показать ограничения STRESS',exact:true}).click();await waitCost();await expect(page.getByTestId('budget-strip')).toContainText('Лимит STRESS');});
 await screenshot('stress-laptop',page.locator('#stress'));
 await check('advanced analysis from population',async()=>{await expect(page.locator('#analysis')).toContainText('Лестница надбавки на оптимизм');await expect(page.locator('#analysis')).toContainText('143 / 1 370,4');await expect(page.locator('#analysis')).toContainText('-220,4');});
 await check('keyboard control and focus',async()=>{const select=page.getByLabel('Режим 1',{exact:true});await select.focus();await expect(select).toBeFocused();await page.keyboard.press('Home');await page.keyboard.press('Enter');await select.selectOption('C');await waitCost();});
 await check('duplicate lot unavailable',()=>expect(page.getByLabel('Лот 2',{exact:true}).locator('option[value="AGRI"]')).toHaveJSProperty('disabled',true));
 await page.getByLabel('Название текущего варианта').fill('Проверенный вариант');await waitCost();
 await page.getByRole('button',{name:'Добавить в сравнение',exact:true}).click();
 await page.getByLabel('Режим 2',{exact:true}).selectOption('C');await page.getByLabel('Название текущего варианта').fill('Нарушение ядра');
 await check('infeasible state has text',()=>expect(page.getByTestId('stress-summary-STRESS')).toContainText('FAIL'));
 await page.getByRole('button',{name:'Добавить в сравнение',exact:true}).click();
 await check('two real alternatives',()=>expect(page.getByRole('region',{name:'Сравнение альтернатив',exact:true})).toContainText('Нарушение ядра'));
 await screenshot('comparison-laptop',page.locator('#comparison'));
 await page.getByRole('button',{name:'Открыть «Проверенный вариант»',exact:true}).click();await waitCost();
 await check('remove alternative',async()=>{await page.getByRole('button',{name:'Удалить Нарушение ядра',exact:true}).click();await expect(page.getByRole('button',{name:'Открыть «Нарушение ядра»',exact:true})).toHaveCount(0);});
 await check('JSON export/import recomputes',async()=>{await waitCost();const p=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать JSON',exact:true}).click();const d=await p;const target=out+'/workspace.json';await d.saveAs(target);await page.getByLabel('Режим 1',{exact:true}).selectOption('A');await page.getByLabel('Файл JSON для импорта',{exact:true}).setInputFiles(target);await waitCost();});
 await check('invalid JSON preserves settings and hides results',async()=>{await page.getByLabel('Файл JSON для импорта',{exact:true}).setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{')});await expect(page.getByRole('alert')).toContainText('Импорт не выполнен');await expect(cost()).toHaveCount(0);await page.getByRole('button',{name:'Пересчитать текущие настройки',exact:true}).click();await waitCost();});
 await check('rapid changes settle to latest',async()=>{for(const value of ['A','B','C'])await page.getByLabel('Режим 1',{exact:true}).selectOption(value);await waitCost();await expect(page.getByLabel('Режим 1',{exact:true})).toHaveValue('C');});
 await check('reload persistence',async()=>{await page.reload();await load().waitFor({timeout:90000});await waitCost();});
 await check('reset and undo',async()=>{await page.getByRole('button',{name:'Сбросить всё',exact:true}).click();await expect(page.locator('#stress')).toContainText('Сначала выберите четыре лота');await page.getByRole('button',{name:'Отменить изменение',exact:true}).click();await waitCost();});
 await check('known cap FAIL without changing price',async()=>{await setRows([['FIRE','A'],['FLOOD','A'],['INFRA','B'],['ENV','A']]);await waitCost('1 297');await expect(page.getByTestId('stress-summary-BASE')).toContainText('+3');await expect(page.getByTestId('stress-summary-STRESS')).toContainText('-117');await expect(page.getByTestId('stress-summary-STRESS')).toContainText('FAIL');});
 await check('contract option executes canonically',async()=>{await setRows([['AGRI','A'],['ENV','A'],['FLOOD','A'],['TRANS','A']]);await waitCost('1 186,5');await page.locator('#stress').getByRole('button',{name:'Исполнить опцион',exact:true}).click();const after=page.locator('#stress .stress-card').filter({hasText:'STRESS · после опциона'});await expect(after).toContainText('PASS');await expect(after).toContainText('1 174');await load().click();await waitCost();});
 await check('search strategy loads real composition',async()=>{const btn=page.locator('#decision').getByRole('button',{name:'Открыть стратегию',exact:true}).first();await btn.waitFor({timeout:90000});await btn.click();await expect(cost()).toBeVisible();await load().click();await waitCost();});
 await check('three actual PDF downloads',async()=>{for(const name of ['Управленческая записка PDF','Стресс-резюме PDF','Презентация PDF']){const p=page.waitForEvent('download');await page.getByRole('button',{name,exact:true}).click();const d=await p;const dest=out+'/'+d.suggestedFilename();await d.saveAs(dest);const b=await fs.readFile(dest);expect(b.subarray(0,5).toString()).toBe('%PDF-');proof.downloads.push({name,file:d.suggestedFilename(),size:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')});}});
 await page.setViewportSize({width:390,height:844});
 await check('narrow layout and every section navigation',async()=>{for(const id of ['overview','builder','comparison','stress','analysis','implementation']){await page.getByRole('navigation').locator('a[href="#'+id+'"]').click();await expect(page.locator('#'+id)).toBeInViewport();const bounds=await page.evaluate(()=>({w:innerWidth,s:document.documentElement.scrollWidth}));expect(bounds.s).toBeLessThanOrEqual(bounds.w);await screenshot('narrow-'+id);}});
 await check('controlled server error and retry',async()=>{await page.route('**/api/workspace/recompute',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Проверочная недоступность'}})}));await page.getByLabel('Название текущего варианта').fill('После ошибки');await expect(page.getByRole('alert')).toBeVisible();await expect(cost()).toHaveCount(0);await page.unroute('**/api/workspace/recompute');await page.getByRole('button',{name:'Пересчитать текущие настройки',exact:true}).click();await waitCost();});
 expect(proof.errors).toEqual([]);expect(proof.external).toEqual([]);expect(proof.console.filter(x=>x.type==='error'&&!x.expected)).toEqual([]);proof.status='PASS';
} catch(e){proof.status='FAIL';proof.failure=e.stack;throw e;}
finally{await fs.writeFile(out+'/result.json',JSON.stringify(proof,null,2));await context.close();await browser.close();}
